version: "3"
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    links:
      - db:db
    volumes:
      - "./app:/usr/src/app"
    command: sh utils/startapp.dev.sh
    tty: true
    stdin_open: true
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - "./db/datadir:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "dev_rails_user"
      POSTGRES_PASSWORD: "dev_rails_password"
      POSTGRES_DB: "dev_rails_db"
